CREATE TABLE IF NOT EXISTS up_tasks_priority
(
	ID INT NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(255) NOT NULL,
	PRIMARY KEY(ID)
);

CREATE TABLE IF NOT EXISTS up_tasks_task
(
	ID INT NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(255) NOT NULL,
	DESCRIPTION VARCHAR(510),
	ID_PRIORITY INT NOT NULL,
	DATE_CREATION DATETIME NOT NULL,
	PRIMARY KEY(ID),
	FOREIGN KEY FK_TASK_STATUS(ID_PRIORITY)
		REFERENCES up_tasks_priority(ID)
		ON UPDATE RESTRICT
		ON DELETE CASCADE
);